version: '3.8'

include:
    - ./AirlinesAPI/docker-compose.yml

services:
    vue-build:
        container_name: airlines-vue-build
        image: node:alpine
        volumes:
            - ./AirlinesWeb:/src:ro
            - vue-app:/app
        networks:
            - vue-net
        working_dir: /app/src
        environment:
            OUTPUT_DIR: /app
        entrypoint: sh -c "cp -afr /src/. /app/src && npm install && npm run build"

    vue:
        container_name: airlines-vue
        image: toarexer/spaserver
        volumes:
            - vue-app:/www
        networks:
            - vue-net
        ports:
            - "8080:80"
        depends_on:
            vue-build:
                condition: service_completed_successfully
            web:
                condition: service_started
            phpmyadmin:
                condition: service_started

volumes:
    vue-app:
        name: airlines-vue-app

networks:
    vue-net:
        name: airlines-vue-network
