version: "3.8"

services:
    db:
        extends:
            file: ./docker/docker-services.yml
            service: db
        networks:
            - internal-net
        volumes:
            - sql-db:/var/lib/mysql

    phpmyadmin:
        extends:
            file: ./docker/docker-services.yml
            service: phpmyadmin
        networks:
            - internal-net
        ports:
            - ${PMA_PORT:-8000}:80
        depends_on:
            db:
                condition: service_started

    app:
        extends:
            file: ./docker/docker-services.yml
            service: app
        networks:
            - internal-net
        volumes:
            - ./AirlinesAPI/:/www
            - ./docker/conf/.env:/www/.env

    web:
        extends:
            file: ./docker/docker-services.yml
            service: web
        networks:
            - internal-net
        volumes:
            - ./AirlinesAPI/:/www:rw
            - ./docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/conf/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - ${WEB_PORT:-5000}:80
        depends_on:
            db:
                condition: service_started
            app:
                condition: service_started

    vue-build:
        extends:
            file: ./docker/docker-services.yml
            service: vue-build
        environment:
            VITE_API_URL: http://web:80/api
        networks:
            - internal-net
        volumes:
            - ./AirlinesWeb:/src:ro
            - vue-app:/app

    vue:
        extends:
            file: ./docker/docker-services.yml
            service: vue
        networks:
            - internal-net
        volumes:
            - vue-app:/usr/local/apache2/htdocs/
        ports:
            - ${VUE_PORT:-8080}:80
        depends_on:
            web:
                condition: service_started
            vue-build:
                condition: service_completed_successfully

    selenium-hub:
        image: selenium/hub:4.0.0
        networks:
            - internal-net

    node-firefox:
        image: selenium/node-firefox:4.17.0-20240123
        shm_size: 2gb
        depends_on:
            selenium-hub:
                condition: service_started
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        networks:
            - internal-net

    selenium-tests:
        image: mcr.microsoft.com/dotnet/sdk:8.0
        volumes:
            - ./AirlinesWeb.Tests:/selenium-tests
            - ./AirlinesWeb.Tests:/testresults
        depends_on:
            selenium-hub:
                condition: service_started
            node-firefox:
                condition: service_started
            vue:
                condition: service_started
        command: >
            /bin/bash -c "dotnet test --logger \"liquid.md;logfilename=/testresults/README.md\" ./selenium-tests/AirportWebTest.csproj"
        networks:
            - internal-net

volumes:
    sql-db:
    vue-app:

networks:
    internal-net:
