<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FlightSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('flights')->insert([
            [
                'id' => 1,
                'airline_id' => 4,
                'origin_id' => 1,
                'destination_id' => 5,
                'distance' => 2100,
                'flight_time' => 300,
                'huf_per_km' => 40,
            ],
            [
                'id' => 2,
                'airline_id' => 1,
                'origin_id' => 2,
                'destination_id' => 10,
                'distance' => 450,
                'flight_time' => 540,
                'huf_per_km' => 50,
            ],
            [
                'id' => 3,
                'airline_id' => 2,
                'origin_id' => 2,
                'destination_id' => 1,
                'distance' => 1080,
                'flight_time' => 650,
                'huf_per_km' => 60,
            ],
            [
                'id' => 4,
                'airline_id' => 3,
                'origin_id' => 2,
                'destination_id' => 3,
                'distance' => 5800,
                'flight_time' => 420,
                'huf_per_km' => 70,
            ],
            [
                'id' => 5,
                'airline_id' => 5,
                'origin_id' => 10,
                'destination_id' => 2,
                'distance' => 4500,
                'flight_time' => 540,
                'huf_per_km' => 80,
            ],
            [
                'id' => 6,
                'airline_id' => 7,
                'origin_id' => 3,
                'destination_id' => 4,
                'distance' => 2800,
                'flight_time' => 320,
                'huf_per_km' => 45,
            ],
            [
                'id' => 7,
                'airline_id' => 6,
                'origin_id' => 5,
                'destination_id' => 11,
                'distance' => 1800,
                'flight_time' => 240,
                'huf_per_km' => 55,
            ],
            [
                'id' => 8,
                'airline_id' => 8,
                'origin_id' => 4,
                'destination_id' => 6,
                'distance' => 9000,
                'flight_time' => 660,
                'huf_per_km' => 55,
            ],
            [
                'id' => 9,
                'airline_id' => 1,
                'origin_id' => 7,
                'destination_id' => 8,
                'distance' => 11000,
                'flight_time' => 780,
                'huf_per_km' => 50,
            ],
            [
                'id' => 10,
                'airline_id' => 2,
                'origin_id' => 9,
                'destination_id' => 10,
                'distance' => 14000,
                'flight_time' => 840,
                'huf_per_km' => 60,
            ],
            [
                'id' => 11,
                'airline_id' => 3,
                'origin_id' => 11,
                'destination_id' => 12,
                'distance' => 2200,
                'flight_time' => 300,
                'huf_per_km' => 70,
            ],
            [
                'id' => 12,
                'airline_id' => 4,
                'origin_id' => 13,
                'destination_id' => 14,
                'distance' => 2000,
                'flight_time' => 280,
                'huf_per_km' => 40,
            ],
            [
                'id' => 13,
                'airline_id' => 5,
                'origin_id' => 15,
                'destination_id' => 16,
                'distance' => 12000,
                'flight_time' => 720,
                'huf_per_km' => 80,
            ],
            [
                'id' => 14,
                'airline_id' => 6,
                'origin_id' => 17,
                'destination_id' => 18,
                'distance' => 900,
                'flight_time' => 660,
                'huf_per_km' => 55,
            ],
            [
                'id' => 15,
                'airline_id' => 7,
                'origin_id' => 19,
                'destination_id' => 20,
                'distance' => 500,
                'flight_time' => 360,
                'huf_per_km' => 45,
            ],
            [
                'id' => 16,
                'airline_id' => 10,
                'origin_id' => 21,
                'destination_id' => 22,
                'distance' => 6500,
                'flight_time' => 600,
                'huf_per_km' => 55,
            ],
            [
                'id' => 17,
                'airline_id' => 2,
                'origin_id' => 21,
                'destination_id' => 2,
                'distance' => 551,
                'flight_time' => 600,
                'huf_per_km' => 55,
            ],
            [
                'id' => 18,
                'airline_id' => 6,
                'origin_id' => 22,
                'destination_id' => 10,
                'distance' => 7500,
                'flight_time' => 570,
                'huf_per_km' => 55,
            ],
            [
                'id' => 19,
                'airline_id' => 4,
                'origin_id' => 23,
                'destination_id' => 2,
                'distance' => 3300,
                'flight_time' => 340,
                'huf_per_km' => 40,
            ],
            [
                'id' => 20,
                'airline_id' => 2,
                'origin_id' => 2,
                'destination_id' => 3,
                'distance' => 5800,
                'flight_time' => 420,
                'huf_per_km' => 60,
            ],
            [
                'id' => 21,
                'airline_id' => 5,
                'origin_id' => 6,
                'destination_id' => 24,
                'distance' => 9000,
                'flight_time' => 660,
                'huf_per_km' => 80,
            ],
            [
                'id' => 22,
                'airline_id' => 6,
                'origin_id' => 24,
                'destination_id' => 25,
                'distance' => 1400,
                'flight_time' => 180,
                'huf_per_km' => 55,
            ],
            [
                'id' => 23,
                'airline_id' => 7,
                'origin_id' => 5,
                'destination_id' => 26,
                'distance' => 5600,
                'flight_time' => 480,
                'huf_per_km' => 45,
            ],
            [
                'id' => 24,
                'airline_id' => 8,
                'origin_id' => 26,
                'destination_id' => 9,
                'distance' => 5600,
                'flight_time' => 480,
                'huf_per_km' => 60,
            ],
        ]);
    }
}
